---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
      - /shared/data/books:/books
      - /shared/data/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
