services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /shared/data/jellyfin/config:/config
      - /shared/data/movies:/movies
      - /shared/data/tvseries:/tvseries
